hostname R2
!
router bgp 65001
 bgp router-id 2.2.2.2

 neighbor 10.0.12.1 remote-as 65010
 neighbor 10.0.24.2 remote-as 65003

 !
 address-family ipv4 unicast

  neighbor 10.0.12.1 route-map CUSTOMER-IN in
  neighbor 10.0.12.1 route-map CUSTOMER-OUT out

  neighbor 10.0.24.2 route-map UPSTREAM-IN in
  neighbor 10.0.24.2 route-map UPSTREAM-OUT out

 exit-address-family
!
route-map CUSTOMER-IN deny 10
!
route-map CUSTOMER-OUT permit 10
!
route-map UPSTREAM-IN permit 10
!
route-map UPSTREAM-OUT deny 10
!
