hostname R3
!
router bgp 65002
 bgp router-id 3.3.3.3

 neighbor 10.0.13.1 remote-as 65010
 neighbor 10.0.34.2 remote-as 65003

 !
 address-family ipv4 unicast

  neighbor 10.0.13.1 route-map CUSTOMER-IN in
  neighbor 10.0.13.1 route-map CUSTOMER-OUT out

  neighbor 10.0.34.2 route-map UPSTREAM-IN in
  neighbor 10.0.34.2 route-map UPSTREAM-OUT out

 exit-address-family
!
route-map CUSTOMER-IN permit 10
 match ip address prefix-list CUSTOMER-R1
!
route-map CUSTOMER-IN deny 100
!
route-map CUSTOMER-OUT permit 10
 match ip address prefix-list UPSTREAM-PREFIX
!
route-map CUSTOMER-OUT deny 100
!
route-map UPSTREAM-IN permit 10
 match ip address prefix-list UPSTREAM-PREFIX
!
route-map UPSTREAM-IN deny 100
!
route-map UPSTREAM-OUT permit 10
 match ip address prefix-list CUSTOMER-R1
 match community CUST-PREPEND-2
 set as-path prepend 65002 65002
!
route-map UPSTREAM-OUT permit 20
 match ip address prefix-list CUSTOMER-R1
!
route-map UPSTREAM-OUT deny 100
!
ip prefix-list CUSTOMER-R1 seq 10 permit 192.0.2.0/24
!
ip prefix-list UPSTREAM-PREFIX seq 10 permit 203.0.113.0/24
!
bgp community-list standard CUST-PREPEND-2 permit 65002:200
!
