hostname R1
!
router bgp 65010
 bgp router-id 1.1.1.1
 neighbor 10.0.12.2 remote-as 65001
 neighbor 10.0.13.2 remote-as 65002
 !
 address-family ipv4 unicast
  neighbor 10.0.12.2 route-map ISP-A-IN in
  neighbor 10.0.12.2 soft-reconfiguration inbound
  network 192.0.2.0/24

  neighbor 10.0.13.2 route-map ISP-B-IN in
  
  neighbor 10.0.12.2 route-map ISP-A-OUT out
  neighbor 10.0.13.2 route-map ISP-B-OUT out
  neighbor 10.0.13.2 send-community
 exit-address-family
!
route-map ISP-A-IN permit 10
 set local-preference 200
!
route-map ISP-A-DEGRADED-IN permit 10
 set local-preference 50
!
route-map ISP-B-IN permit 10
 set local-preference 100
!
route-map DENY-OUT deny 10
!
ip prefix-list OUR-PREFIX seq 10 permit 192.0.2.0/24
!
route-map ISP-A-OUT permit 10
 match ip address prefix-list OUR-PREFIX
!
route-map ISP-A-OUT deny 100
!
route-map ISP-B-OUT permit 10
 match ip address prefix-list OUR-PREFIX
 set community 65002:200
!
route-map ISP-B-OUT deny 100
!
